version: "3.9"

services:
    api:
        build: ./api
        depends_on:
            - postgres
        ports:
            - "8000:8000"
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_HOST: $POSTGRES_HOST
            POSTGRES_PORT: 5432
            POSTGRES_DB: $POSTGRES_DB

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB